# Generated by Django 4.2.9 on 2024-02-20 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100, verbose_name='Игра или сервис')),
                ('character_name', models.CharField(max_length=100, verbose_name='Имя персонажа или ссылка на профиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
